### ISSUE TITLE
Base of logarithm for fold change

### ISSUE THREAD

**Issue by khandarius** [RGLab/MAST#100]
Hi,

Thanks for the great software. My question concerns the results of the differential expression tests performed with the hurdle model and a likelihood ratio test, like you present in your MAIT vignette (https://bioconductor.org/packages/release/bioc/vignettes/MAST/inst/doc/MAITAnalysis.html). I was wondering about the base of logarithm for the logFC coefficient. In the vignette, you set a fold change threshold using the R function log2(), which implies that the coefficients are in base 2. However, I don't see the base explicitly mentioned in the documentation. What about the output of the MAST function logFC()? I would like to be sure of the base for the results I am reporting.

Best regards,
Darius

**Comment by gfinak** [comment]
The base of the logarithm is whatever you set it to be when you log transform your counts.

**Comment by gfinak** [comment]
Can I close this issue?

**Comment by khandarius** [comment]
Hi Greg,

Thanks for the answer, it's clear to me know. The issue can be closed.

Best regards,
Darius
