### ISSUE TITLE
issues of multi-conditions

### ISSUE THREAD

**Issue by jsxlei** [RGLab/MAST#101]
e.g. When I run conditions contain A, B, C, I found the summary only had B, C referenced on A, and A had no results, how to calculate all conditions?

**Comment by gfinak** [comment]
Can you post a reprex, or we can't help you otherwise.

**Comment by jsxlei** [comment]
according to the tutorial, I got this:
##  primerid  conditionStim cngeneson
##  100462981   -6.4*          1.5   
##  152926       6.2*         -2.9   
##  253512       3.2          -4.6*  
##  26054        4.1          -4.6*  
##  3458         7.3*          0.5   
##  3727        -6.7*          0.5   
##  514          3.1          -4.2*  
##  6482         4.5          -6.4*

but, I want DE of conditionUnstim at the same time,
if I have multi conditions, I want them compare each other, not limited to referenced on the same condition.

**Comment by amcdavid** [comment]
Per the README would be been best directed to the bioconductor support site:: https://support.bioconductor.org/, since this not a bug report.  Do either of https://support.bioconductor.org/p/100396/ or https://support.bioconductor.org/p/98420/ answer your question?

**Comment by gfinak** [comment]
Use the `hypothesis` argument and set the contrasts you want to test (which is all of them in your case). This is in the manual and at the links Dr. McDavid posted.

**Comment by jsxlei** [comment]
I got it, Thanks.
