### ISSUE TITLE
python implementation of MAST

### ISSUE THREAD

**Issue by DanSchnell** [RGLab/MAST#102]
Is there a python implementation of MAST?

**Comment by gfinak** [comment]
No.

**Comment by amcdavid** [comment]
No, and nothing planned at the moment.  [`LoomExperiment`](https://bioconductor.org/packages/release/bioc/vignettes/LoomExperiment/inst/doc/LoomExperiment.html) should make it easy to import `loom` files and run them in MAST, though I haven't actually tried it yet.

**Comment by DanSchnell** [comment]
Thanks very much for your quick replies and suggestion!
