### ISSUE TITLE
DE among any two clusters

### ISSUE THREAD

**Issue by AndMass** [RGLab/MAST#106]
Hi!

I'm trying MAST for differential analysis in a scRNA-seq experiment after clustering, i.e. I don't have any treatment vs control, but I'm interested in all possible differences in expression between two or more clusters.
I tried following the examples:

```
obj.mast <- FromMatrix(logcounts(reads.qc.endog), cData = data.frame(wellKey = colnames(reads.qc.endog), sc3k12 = reads.qc.endog$sc3_12_clusters))
                       
colData(obj.mast)$cngeneson <- scale(colSums(assay(obj.mast) > 0))
                       
zlm.k12 <- zlm(~sc3k12 + cngeneson, obj.mast)
summary.k12 <- summary(zlm.k12, doLRT = "sc3k12")
summaryDt.k12 <- summary.k12$datatable

```

While it works, this only gives the DE of clusters 1v2, 1v3, 1v4 and so on, as the first level is taken as reference.

I unsuccessfully tried to modify the code to get all other comparisons, i.e. 2v3, 2v4, 3v4...11v12.
What am I missing?

Thanks!
Andrea

**Comment by gfinak** [comment]
You fit the correct model, but want you need to do is test the correct contrasts.
the `Hypothesis()` function is what you want to use.
If you have coefficients for the intercept (which encompasses c1), c2, and c3 then to test c2 vs c3 you would test the linear hypothesis that `c2-c3 == 0` which is the same as `intercept + c2 - (intercept + c3) == 0`

**Comment by AndMass** [comment]
Thanks Greg, 
I created contrast matrices with `Hypothesis()`, however when I pass them to the doLRT argument in `summary()` above, I get the following error:
```
Combining coefficients and standard errors
Calculating log-fold changes
Calculating likelihood ratio tests
Error in generateHypothesis(hypothesis, colnames(object@coefD)) : 
  Term(s) '(Intercept)-sc3k12c2 ,' not found.
Terms available: (Intercept) , sc3k12c2 , sc3k12c3 , sc3k12c4 , sc3k12c5 , sc3k12c6 , sc3k12c7 , sc3k12c8 , sc3k12c9 , sc3k12c10 , sc3k12c11 , sc3k12c12 , cngeneson , 
Calls: summary ... lapply -> FUN -> lrTest -> lrTest -> generateHypothesis
Execution halted 
```
do I have to pass it to `zlm()` instead?
Or to an `lrTest()` ran on the ZlmFit created by `zlm`? And in this case how would I get the `data.table` at the end from the array produced by `lrTest()`?

Thanks a lot,
Andrea

**Comment by gfinak** [comment]
Perhaps @amcdavid can comment on the interface?

Greg Finak

**Comment by gfinak** [comment]
@AndMass I believe you need to pass it along with the fitted model object to lrTest.

**Comment by amcdavid** [comment]
As Greg pointed out, no need to include the `(Intercept)` when you form the contrasts, because you are just adding and subtracting it from both sides.  But if for some reason you did need to include it, you have to escape it with backquotes like this
```
data(vbetaFA)
zlmVbeta <- zlm(~ Stim.Condition, subset(vbetaFA, ncells==1)[1:10,])
lrTest(zlmVbeta, Hypothesis('`(Intercept)`'))
```
Note there is a warning emitted telling you that, as well.
