### ISSUE TITLE
Random effects

### ISSUE THREAD

**Issue by livnatje** [RGLab/MAST#107]
Hi!

Is it possible to use MAST with random effects? For example, when the cells were sampled from different patients (y ~ conditions + nGenes + (1 | patients), instead of y ~ condition + nGenes + patients).

Thanks!
Livnat

**Comment by gfinak** [comment]
Hi, @livnatje
Sorry for the delay responding. You can pass `method="glmer"` to `zlm` but you'll also have to pass `ebayes=FALSE`
