### ISSUE TITLE
Problem with the mast_filter

### ISSUE THREAD

**Issue by pandhey** [RGLab/MAST#111]
Hi, 
when I am trying to use dplyr filter function getting an error from MAST package "Warning message:
'filter' is deprecated.
Use 'mast_filter' instead.
See help("Deprecated")
Execution halted"

i think it's replacing the dplyr filter function. so couldn't use filter when I install MAST package.

**Comment by gfinak** [comment]
use `dplyr::filter` in your code.
`filter` in Mast is deprecated and will eventually be removed.

**Comment by amcdavid** [comment]
Or make sure that you run library('dplyr') after library('MAST') so that MAST is being masked, rather than doing the masking.
