### ISSUE TITLE
Error in parse(text = x, keep.source = FALSE) :   <text>:2:0: unexpected end of input

### ISSUE THREAD

**Issue by wenjuanZHU2018** [RGLab/MAST#113]
Dear sir/madam, 

over the last few days, I was working on MAST. However,  it always tells me these following information. My input file and R script could be found below. I really appreciate it if you could help me find out the problems.   
Error in parse(text = x, keep.source = FALSE) :
  <text>:2:0: unexpected end of input
1: ~
   ^
Calls: <Anonymous> ... formula -> formula.character -> formula -> eval -> parse
In addition: Warning message:
In .nextMethod(object = object, value = value) :
  Coefficients (Intercept), conditionControl, cngeneson are never estimible and will be dropped.
Execution halted. 

2: R script 
library("data.table")
library("dplyr")
library(MAST)
#===read file=========
raw.data <-read.table("aa.txt", sep = "\t", header = TRUE)
raw.anno <-read.table("bb.txt", sep = "\t", header = TRUE)
keep  <- raw.anno[,2] == "ACC"
anno  <- raw.anno[keep,]
keep  <- c(TRUE,keep)
data  <- raw.data[,keep]
Genename <- data[,1]
data.exp <- data[,-1]
#data.exp
rownames(data.exp)=Genename
diagnosis    <- anno[,3]
gkeep      <- rowSums(data.exp > 0) > 0
counts     <- data.exp[gkeep,]
log_counts <- counts/1;
#log_counts <- log(counts+1)/log(2);
fData = data.frame(primerid=rownames(log_counts))
rownames(fData) = rownames(log_counts)
cData = data.frame(condition=diagnosis)
rownames(cData) = colnames(log_counts)
obj <- FromMatrix(as.matrix(log_counts), cData, fData,check_sanity = FALSE)
colData(obj)$cngeneson <- scale(colSums(assay(obj)>0))
cond <- factor(colData(obj)$condition)
colData(obj)$condition <-cond
dim(obj)
zlmCond <- zlm(~cond + cngeneson, obj, method = "glmer", ebayes = F, silent=T)
summaryCond <- summary(zlmCond, doLRT="cond_ACC")
summaryDt <- summaryCond$datatable
summaryDt <- as.data.frame(summaryDt)
head(summaryDt)
pVals <- unlist(summaryDt[summaryDt$component == "H",4])
names(pVals) <- unlist(summaryDt[summaryDt$component == "H",1])
pVals <- p.adjust(pVals, method = "fdr")
write.csv(pVals,file="Correct_pVals.txt")

 
3: aa.txt 
Gene	1823_BA24.GTCCTCAAGACTAGGC	1823_BA24.GTCATTTCAGCAGTTT	1823_BA24.TCTGAGAAGTGTTTGC	1823_BA24.CTCTACGGTCCGCTGA	1823_BA24.GCAGCCATCGCAAACT	1823_BA24.TCTCTAATCCTTGACC	1823_BA24.CAAGTTGCAAAGCAAT	1823_BA24.CCTTCGAAGGATGGAA	1823_BA24.CCTCTGACAGCTATTG	1823_BA24.CCTACACAGTGGTCCC	1823_BA24.CAAGGCCTCCCATTAT	1823_BA24.CTCTGGTGTAGAGTGC	1823_BA24.GCGGGTTCAGTGGGAT	1823_BA24.TGCGTGGCACCAGTTA	1823_BA24.CTCTAATAGAGGTTAT	1823_BA24.GTACTTTGTATGAATG	1823_BA24.GGGATGACAATCGGTT	1823_BA24.TTCCCAGCAGTCGTGC	1823_BA24.CTCGGAGGTTTGGCGC
Gene1	10	10	10	10	5.106719184588718	10	10	10	10	10	10	10	10	10	10	10	10	10	10
Gene110	10	10	10	10	5.106719184588718	7.1548731073108276	10	8.4755128561071011	10	10	10	10	10	10	10	8.810519231010761103	10	10	10
Gene11	10	10	10	10	10	6.64463215624248	10	10	10	10	10	10	10	10	10	4.852775876124106	10	10	10
Gene12	10	10	10	10	10	10	10	10	10	10	10	10	10	10	10	10	10	10	10
Gene15	10	10	10	10	10	10	11.9241025886321	10	10	10	10	10	10	10	10	10	10	10	10
Gene17	10	10	10	10	9.665286121610463	8.633777102574862	10	10	10	10	10	10	10	10	10	10	10	10	10
Gene18	10	10	10	10	10	10	10	10	10	10	10	10	10	10	10	10	10	7.63415549338775	10
Gene19	10	10	10	10	10	10	10	10	10	10	10	10	10	10	10	10	8.82107610106345541	10	10
Gene210	10	10	10	10	7.67826336347984	10	10	10	10	10	10	10	110.1862929912618	10	10	10	10	10	10
Gene7	10	10	10	10	9.34283894752954	110.11094942215443	10	10	10	10	10	10	11.5641042436965	10	10	7.395521010332862	10	10	10
Gene8	10	10	10	10	1.66374276255473	10	10	10	10	10	10	7.32131461271557	10	10	10	10	10	6.323107969238257	10
Gene9	13.1032544557765	14.14106964336278	9.4719516108141108	10	110.5121064753917	11.65189933410977	12.1166245552777	6.8986339341010249	12.471102554110548	12.36974844108716	110.10431052510710477	10	10	10	110.61105635103925	9.3891079356631108	10	10	10
GeneA	10	10	10	10	2.9107875674610368	7.33425379269757	10	10	10	10	10	9.314533191022623	10	10	10	5.827593410945154	10	10	10
GeneB	10	10	10	6.21210146121071048	5.94753711059998	10	10	10	12.3641298839298	10	10	10	10	10	10	10	10	10	10
GeneG	10	10	10	10	9.6310188125817	8.633777102574862	7.899961010848710108	8.889536715891023	10	6.711088859911619	10	10	12.10922752792938	10	10	10	10	10	10
4: bb.txt
cell	region	diagnosis
1823_BA24.GTCCTCAAGACTAGGC	ACC	Case
1823_BA24.GTCATTTCAGCAGTTT	ACC	Case
1823_BA24.TCTGAGAAGTGTTTGC	ACC	Case
1823_BA24.CTCTACGGTCCGCTGA	ACC	Case
1823_BA24.GCAGCCATCGCAAACT	ACC	Case
1823_BA24.TCTCTAATCCTTGACC	ACC	Case
1823_BA24.CAAGTTGCAAAGCAAT	ACC	Case
1823_BA24.CCTTCGAAGGATGGAA	ACC	Case
1823_BA24.CCTCTGACAGCTATTG	ACC	Case
1823_BA24.CCTACACAGTGGTCCC	ACC	Control
1823_BA24.CAAGGCCTCCCATTAT	ACC	Control
1823_BA24.CTCTGGTGTAGAGTGC	ACC	Control
1823_BA24.GCGGGTTCAGTGGGAT	ACC	Control
1823_BA24.TGCGTGGCACCAGTTA	ACC	Control
1823_BA24.CTCTAATAGAGGTTAT	ACC	Control
1823_BA24.GTACTTTGTATGAATG	ACC	Control
1823_BA24.GGGATGACAATCGGTT	ACC	Control
1823_BA24.TTCCCAGCAGTCGTGC	ACC	Control
1823_BA24.CTCGGAGGTTTGGCGC	ACC	Control

**Comment by wenjuanZHU2018** [comment]
Many thanks for all your help.

**Comment by gfinak** [comment]
Please have a look at this package: https://github.com/tidyverse/reprex
and use it to produce a minimal reproducible example that you can paste into this bug report.

**Comment by gfinak** [comment]
This is related to #114 I'll close this issue and work on it there.

**Comment by amcdavid** [comment]
@wenjuanZHU2018 is trying to run a random effects model with lmer, but didn't include any random effects.  If a random effect is specified, it works just fine.  This model is statistical non-sense but does serve to illustrate the functionality:
```
zlmVbeta <- zlm(~ Stim.Condition + (1|Well), subset(vbetaFA, ncells==1)[1:10,], method='glmer', ebayes=F, silent=T)
```
Set `method = 'bayesglm'` if there aren't any random effects.

We could try to signal a more intelligible error here.  We do some fairly dark magic to the formula to be able to run arbitrary likelihood ratio tests and it's probably not ever going to 100% robust.

**Comment by arr951** [comment]
I am creating a plot using ggplot2, and when I use "directlabels" package, I get the same error message that other people reported here (above).  "(**Error in parse(text = elt) : <text>:2:0: unexpected end of input 1: ~ ^**),  and I can NOT create the labels for the lines.
But I use the a different computer the same codes work fine with no error message, and I am able to create the Labels for each line. I googled this, but was unable to fix it.

Has anyone had similar experience, and knows how to fix this? I even uninstalled and reinstalled R and RStudio, and got the latest versions of the packages. But it still didn't work.

Your help is greatly appreciated!

**Comment by amcdavid** [comment]
We can't possibly help without a reproducible example. Feel free to open a new issue once you have one.  As Greg said just a few comments above:

> Please have a look at this package: https://github.com/tidyverse/reprex
> and use it to produce a minimal reproducible example that you can paste into this bug report.
