### ISSUE TITLE
Travis builds always timeout

### ISSUE THREAD

**Issue by amcdavid** [RGLab/MAST#116]
@gfinak @mikejiang 
We continually have a big ugly "error" badge on README.md because we exceed the time limit for the travis builds.  Can we find a way to use travis without exceeding the time limit?  Or just remove the badge and post a link to the Bioconductor package builder?

**Comment by gfinak** [comment]
FWIW here's the current bioconductor dev build status
http://bioconductor.org/checkResults/devel/bioc-LATEST/MAST/
also erroring.

**Comment by amcdavid** [comment]
Yeah that's because Aaron removed the data we were using in scran without
deprecating it... It's back in scran for now.

**Comment by amcdavid** [comment]
Fixed in 00c1232 and 0a9fe9
