### ISSUE TITLE
DE among experimental and control group

### ISSUE THREAD

**Issue by chendianyu** [RGLab/MAST#118]
Hi,

I'm trying MAST for differential analysis in a scRNA-seq experiment. I have some experimental and control batches, like "exp1", "exp2", "exp3", "ctrl1", "ctrl2", and I use Seurat  to integrate them and perform clustering. Now I want to find differential expressed genes between experimental and control group for each cluster, but I do not know how to do. I have tried codes like something below, but it didn't work.

zlm.output <- zlm(~ batches, sca.1)
lrTest(zlm, Hypothesis('(exp1+exp2+exp3)/3 - (ctrl2+\`Intercept\`)/2')

Any suggestions?

Thanks!
Dianyu Chen

**Comment by amcdavid** [comment]
Can you please post your question on the bioconductor support site?  The github issues are just for bugs because once the issue is closed, it's not searchable by anyone else.
https://support.bioconductor.org/
