### ISSUE TITLE
comparing 2 models with confounders

### ISSUE THREAD

**Issue by massonix** [RGLab/MAST#123]
Dear RGLab,

I want to conduct a differential expression analysis between two groups including covariates in my analysis in a manner similar to this article: https://science.sciencemag.org/content/sci/suppl/2019/05/15/364.6441.685.DC1/aav8130_Velmeshev_SM.pdf .  They say that "To identify genes differentially expressed due to the disease effect, likelihood ratio test (LRT) was performed by comparing the model with and without the diagnosis factor". Analogously, I would constract the following two models:

zlm_signal <- zlm(~ is_cancer + bias_score, sca)
zlm_background <- zlm(~ bias_score, sca)

Thus, comparing both models I could avoid finding genes that vary due to "bias_score", and only detect those that are important in cancer. Could I use a likelihood test for that? If so, how?

Thanks a lot in advance!

Best

Ramon

**Comment by gfinak** [comment]
Please post this question to the Bioconductor list.
Github is for bug tracking
