### ISSUE TITLE
About obtaining DE genes

### ISSUE THREAD

**Issue by ahmedabbas81** [RGLab/MAST#124]
Dear all,
 
In the Methods section, in the subsection, Testing for differential expression, it is mentioned that a gene is considered differentially expressped if FDR adjusted p-value is < 0.01 and estimated fold-change is greater than 1.5 (on a log2 scale).
 
For the estimated fold change, does the paper mean that avg_logFC > 1.5 or FC > 1.5 and avg_logFC > 0.58 (knowing that log2(1.5) = 0.58)?
 
Also, it is not clear to me how the p-value was calculated?
 
Thank you
Ahmed

**Comment by ahmedabbas81** [comment]
Can you please answer?

**Comment by amcdavid** [comment]
"Issues" are for bug reports only.  Please read the instructions on the README. Methods/applications questions are to be posted on support.bioconductor.org

**Comment by ahmedabbas81** [comment]
Ok, thanks. I posted it on support.bioconductor.org
