### ISSUE TITLE
Creating a package that depends on glmer in MAST

### ISSUE THREAD

**Issue by kdzimm** [RGLab/MAST#126]
Hey MAST makers,

Big fan of your work. The best single-cell RNA-seq analysis package currently out there that I know of. Apologies if I am not doing this in the right spot, I am new to making R packages and new to GitHub, and this seemed like the only spot to ask questions. 

I have come across and issue that I can't seem to solve, but it appears to be related to how my package (currently in development) is pulling in and using the glmer function in MAST. I am using this line of code in one of my functions:

zlmCond <- suppressMessages(MAST::zlm(~ Status + (1 | DonorID), sca, method='glmer',ebayes = F))

which spits back this error when I run the function in my code:

Error in fixef(object@fitC) : could not find function "fixef" 

If I load the 'lme4' package within my function prior to running that component, it works (which I read in Wickham's "R packages" that this is something to avoid, so I am trying to avoid doing it this way). At first it was a problem with the 'fixef' function somewhere missing 'lme4::', but when I looked through your .R files, I noticed this was not the case, all are lme4::fixef() . Any ideas what I am doing incorrectly? Again, sorry to waste your time with this if I am doing something stupid here. I am still very new to all of this.

Thanks so much!

Kip

**Comment by amcdavid** [comment]
I suspect this is because you have an older version of MAST installed.  The scoped access to fixef was added somewhat recently [19-July-2019](https://github.com/RGLab/MAST/commit/acbfce1a3f9d3fb093b26213eb25aa632152022a).  Try the most recent version included in this release of bioconductor (1.12.0) or the one here on github (which may require R devel 4.0, which is painful to install).

**Comment by kdzimm** [comment]
You are probably right, I am using 1.8.2. I will let you know if that fixes my problem. Thanks a bunch, @amcdavid !

**Comment by kdzimm** [comment]
@amcdavid  this fixed my problem, however, now it appears I am getting a lot more errors about convergence (complete separation) or the following error "number of levels of each grouping factor must be < number of observations". I was not getting this before. Is this new functionality? The reason I ask is because while the convergence errors make sense, the other error does not seem to make sense to me. I have simulated these data to have many more observations than levels of grouping factor. Sorry to keep bugging you with my problems. Thanks for your help.

**Comment by kdzimm** [comment]
@amcdavid I think these are updates to lme4 and their update to stop returning pvalues via the mcmcsamp function. I will not bother you with this issue and I will close this thread.  I would imagine, however, that this is an important issue for you to think about how these updates affect users trying to use MAST with random effects. Thanks again for your help!

**Comment by amcdavid** [comment]
Yes, the above messages are due to changes in lme4.  I don't think it actually affects the return values, but the criteria for emitting a warning seems to have changed.

**Comment by kdzimm** [comment]
Sorry to reopen this, but I can't figure out why all my values from the 'H' component of the summary table for the following model are NA. I've simulated 20,000 genes under the null (and I have even further simulated more cells for each of the individuals so I am not getting the error up above), and every single one of them returns NA for the 'H' component. 

zlmCond <- MAST::zlm(~ ngeneson + Status + (1 | DonorID),
                                          sca, method='glmer',
                                          ebayes = F,
                                          strictConvergence = FALSE)

I thought about using the 'z' value from the logFC component, (thinking the logFC is a function of both the discrete and continuous components so the wald test and LRT should asymptotically arrive at the same conclusion, but when I drop the random effects to make sure they are asymptotically equivalent with large sample sizes, they don't seem to be). 

To be clear, my two issues are:

1) All my 'H' components when I include a random effect for individual in my model go to NA. I thought this was a result of updates to lme4, but you seem to think their updates shouldn't affect output/return values? Any idea why this is happening? The only difference in my two are literally the addition of '+ (1 | DonorID)' (For the record, this was not previously a problem before updating my R and R packages)

2) Why aren't the wald test for logFC and the LRT for the 'H' component converging? Aren't they testing the same hypothesis? This is probably just a misunderstanding about what your logFC is, but I thought it was just the estimate for the variable being tested?

**Comment by gfinak** [comment]
I think it would help if you tell us how you simulated your data, maybe even post a [reprex](https://reprex.tidyverse.org/articles/articles/learn-reprex.html)

**Comment by kdzimm** [comment]
I can work towards building a reprex (I've never used it before, but it looks pretty straightforward). I also have not published this yet, so a little hesitant to post all of my code. 
In brief, I modeled distributions and relationships empirically of single cell data. I modeled grand mean as a gamma distribution, and then modeled inter- and intra-individual variation as function of the grand mean. Gene wise dropout too. Then overlayed cell wise dropout and used a dirichlet distribution with simulated library sizes to build the counts. Probably too simple of an explanation, but hopefully you get the idea. 

If you run typical single cell data through MAST with random effects (on updated versions of course) are you able to get non-"NA" values for the 'H' component? Is my simulated data what is causing this? This is something I will try really quickly and see before I do anything else. If so that is helpful information either way. 

Thanks for the quick reply.

**Comment by kdzimm** [comment]
Is there anywhere I can share my code in a place that is not public?

**Comment by amcdavid** [comment]
I think there has been a regression in the lmer code since MAST 1.8.2.  Seems to be independent of lme4 version.  

R_LIBS_USER=~/Library/R/3.8-bioc/ R --no-environ
```

> R version 3.5.2 (2019-12-12) -- "Dark and Stormy Night"
> Copyright (C) 2019 The R Foundation for Statistical Computing
> Platform: x86_64-apple-darwin15.6.0 (64-bit)

```r
knitr::purl('vignettes/MAST-Intro.Rmd')
source('MAST-Intro.R')
lmer.output <- zlm(~ Stim.Condition +(1|Subject.ID), vbeta.1, method='glmer', ebayes=FALSE)
lrt = lrTest(lmer.output, 'Stim.Condition')
summary(lrt[, 'hurdle', 'lambda'])
```
> Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
>   0.000   2.685   5.907  12.751  14.731  53.542 

vs when I load 1.13.3

> summary(lrt[, 'hurdle', 'lambda'])
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
      0       0       0       0       0       0      19

**Comment by amcdavid** [comment]
Pretty sure [this](https://github.com/RGLab/MAST/blob/0cb1a1941cf1ecfe4f2d5a594018c78ba65bd18b/R/lmWrapper-glmer.R#L305) is the culprit

**Comment by kdzimm** [comment]
Good catch, thanks for looking at this. Is it still helpful if I post my code? What do you need from me to help you get to the bottom of this? 

Thank you for looking into this @amcdavid and @gfinak. And thank you for working so quickly to help me! I am sure you have many other things to be working on today.

**Comment by amcdavid** [comment]
@kdzimm give the most recent version 1.13.4 a try and let me know if that fixes things.

**Comment by kdzimm** [comment]
That did the trick! Thank you soooo much! Really appreciate it!
