### ISSUE TITLE
Nameless Gene column

### ISSUE THREAD

**Issue by drmofjv** [RGLab/MAST#127]
Hello,
I have a couple of issues with my DE analysis using MAST and since I am new to using R, I don't seem to be able to fix them. 
1. In my output, there is no name for my column containing the genes, and for later plots I should be able to refer to this column.. All the other colums for FC etc are named, only the one with genes is not.
The code I used for DE calculation is:
somatotrope.de.markers.c.yo <- FindMarkers(data_seurat_c_somato, ident.1 = "Young", ident.2 = "Old", test.use = "MAST", latent.vars = c("nUMI","percent.mito"), logfc.threshold = 0, min.pct = 0, min.cells.group = 0, verbose = FALSE)

2. I calculated DE gene expression between 2 conditions for every cluster seperately and then I merged all the tables into 1 object. However, when I exported this object as a .txt file, I noticed that sequential numbers were added to the gene names when a gene was present in different clusters. So for cluster 1 the gene was called 'gene' in cluster 2 it was 'gene1', cluster 3 'gene2' and so on. Which is off course quite confusing.  
The code I used here is:
yo_c_deg<-rbind(CT.de.markers.c.yo, cortico.de.markers.c.yo, dying.de.markers.c.yo, endothelia.de.markers.c.yo, gonad.de.markers.c.yo, mito.de.markers.c.yo, lacto.de.markers.c.yo, melano.de.markers.c.yo, somatotrope.de.markers.c.yo, stem.de.markers.c.yo, thyro.de.markers.c.yo, wbc.de.markers.c.yo)
head(yo_c_deg)
write.table(yo_c_deg, "DEG_control_young_vs_old2.txt",col.names=NA, row.names = FALSE, sep="\t")

Thanks for your time!

**Comment by gfinak** [comment]
So, I don't know exactly what Seurat is doing under the hood when it uses MAST. Generally your input should be a SingleCellExperiment derived object with featureData set, that's where the gene names should be assigned. 
MAST uses a SingleCellAssay object which derives from SingleCellExperiment.
See here: https://bioconductor.org/packages/devel/bioc/vignettes/MAST/inst/doc/MAST-interoperability.html

**Comment by amcdavid** [comment]
@drmofjv I can take a look to see if there is a feature or modification we could add to enhance compatibility with Seurat, but I need an example that I could run/reproduce on my machine.  Can you provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), eg, with one the [example datasets](https://github.com/satijalab/seurat-data) from Seurat?

**Comment by drmofjv** [comment]
@amcdavid thank you for the response, but I was just able to fix it! 
Apparently the problem occured because the genes came out as rownames and I could fix this by transforming rownames into a column using 
wbc.de.markers.c.yo <- tibble::rownames_to_column(wbc.de.markers.c.yo, "Gene").
