### ISSUE TITLE
Request for an explanation about the summary function output

### ISSUE THREAD

**Issue by VicenteFR** [RGLab/MAST#132]
Hi there!

Hope you are all doing well!
Here I am just asking for a wide explanation about the meaning of the columns of the output coming out of the **summary function applied to a ZlmFit object**, specifically the data table component. When I apply it to my data, I get a data table with the columns 'muC', 'etaD', 'seC' and 'seD'. I'm aware each value has something to do with the continuous and discrete parts of the model, but I'd like to know the meaning of each column in detail. 
I guess this must be anywhere else already but I really couldn't find it so I would appreciate any explanation.

**Thanks so much in advance**,
Vicente

**Comment by amcdavid** [comment]
That looks to me like output from calling `predict`, rather than `summary`.  That's not the expected output of `summary`, nor what the example in the help `example("summary,ZlmFit-method")` provides.  Can you provide a reproducible example clarifying what you ran, and what your question is?
