### ISSUE TITLE
Importing CellRanger read count matrix or Seurat object into MAST

### ISSUE THREAD

**Issue by singcell** [RGLab/MAST#134]
I am analyzing data generated by 10x and CellRanger. I am comparing Control and Stimulated samples. In Seurat I create Seurat object using 10x read count matrix and use `FindIntegrationAnchors` and `IntegrateData` to integrate two conditions. I wanted to use MAST to calculate the differential expression between clusters across conditions. 

I wanted to know if there is a way:
 1) I can import 10x read count matrix or Seurat object to input into MAST.
2) if there is a function to import CellRanger read count matrix into MAST.

Thank you

**Comment by gfinak** [comment]
Doesn't Seurat allow you to use MAST as a differential expression method under the hood?
https://satijalab.org/seurat/v3.0/de_vignette.html  (search for MAST)

**Comment by amcdavid** [comment]
And if you need to convert from Seurat into MAST (or other Bioconductor packages), you can do
sce = Seurat::as.SingleCellExperiment(seurat_obj)
MAST::SceToSingleCellAssay(sce)

**Comment by singcell** [comment]
@gfinak @amcdavid 
Thank you
