### ISSUE TITLE
Resource requirements for large sparse matrices

### ISSUE THREAD

**Issue by combiz** [RGLab/MAST#138]
MAST glmer (with a random effect for individual) is our preferred method for sc/sn-RNAseq; however, we're finding that resource requirements on our latest dataset are problematic.  Running DE on a cluster with 52700 cells and 8300 genes (after QC/pre-filtering steps) requires 1.2Tb RAM and runs for 12h+ with 96-cores.  The model is "~hist + (1 | individual) + cngeneson + pc_mito" where `hist` is a numeric dependent var.

These resources requirements are ~6x higher than the same analysis on the next largest celltype (27500 cells / 5500 genes) -- which we are able to run on a 128Gb RAM / 12-core workstation (with swap).

Do you have any suggestions for reducing resource requirements as we deal with increasingly larger datasets/clusters?

**Comment by gfinak** [comment]
No immediate fixes for this.. one idea might be to pass `nAGQ=0` to `glmer`, this could speed up fitting significantly. Not sure of the impact on memory requirements. Also, how many subjects in your data? I'm wondering about the complexity of the random effect part of the model...are cells from each subject present in each cell type? Finally, a statistical consideration..  do you need an n=52K to detect significant differences between cell types?

**Comment by combiz** [comment]
Thanks, Greg.  The `nAGQ=0` parameter gave us a four-fold decrease in running time, though slightly increased RAM usage from 1.2Tb to 1.6Tb.  Together with slightly increasing the stringency of gene pre-filtering, this provides an adequate solution for now.  Good question re: statistical consideration, power calculations for single-cell/nuclei are something we're actively looking into.  Thanks again.

**Comment by amcdavid** [comment]
The memory requirements seem extreme, and might explain also why it's slow if there are a bunch of cache misses.   Do you know what the memory requirements is of the R parent process before you call `zlm`?   Is it roughly ~1.2Tb/96?

We should see about switching the parallel backend from `mclapply` to something more modern (or just `parallel::parSapply` ?) and not dependent on forking, which makes rstudio unhappy anyways.  This would also give more control over the data that is passed to the children processes and might reduce the memory requirements.

**Comment by gfinak** [comment]
@amcdavid  Maybe we should think about moving over to futures?

**Comment by combiz** [comment]
In our case, in addition to applying the `nAGQ=0` parameter, we also opted to reduce the number of cores used (i.e. `<future::availableCores()`), which reduced RAM requirements concomitantly.  Especially when fitting DE models on large numbers of cells, we found this a useful trick to allow analyses to complete on a personal workstation, and to keep costs down in the cloud.

**Comment by gfinak** [comment]
Thanks, @combiz I appreciate the follow up.
