### ISSUE TITLE
Units of logFC for a numeric dependent variable

### ISSUE THREAD

**Issue by combiz** [RGLab/MAST#140]
Could you kindly advise on how to interpret the glmer logFC values for models with a numeric dependent variable?  The units are difficult to infer.

**Comment by amcdavid** [comment]
It's like any other numeric variable in a regression.  A one unit change in dependent `x` causes a `2^(logFC)`-fold change in expression, holding all other coefficients in the model constant.

**Comment by combiz** [comment]
Thanks, this is what we expected until we saw that the magnitude of logFC for some genes was difficult to corroborate visually.  We can now discount one possible explanation and explore alternatives.  Cheers.

**Comment by combiz** [comment]
Thanks, this is what we expected until we saw that the magnitude of logFC for some genes was difficult to corroborate visually.  For example, this gene was fit with glmer (`~hist + (1 | individual) + cngeneson + pc_mito`) and was identified as DE (padj 1.72e-122  and logFC 0.89): -
![image](https://user-images.githubusercontent.com/31043044/87695669-ade1f300-c787-11ea-9683-e191052aa93a.png)
![image](https://user-images.githubusercontent.com/31043044/87695808-dc5fce00-c787-11ea-97b1-727a906c16d4.png)

**Comment by amcdavid** [comment]
The paradoxical sign of the log fold change may because it is extrapolating beyond the range of the data of `pc_mito`.  Best to center `pc_mito`.  The "holding everything else" constant is important for the fold change calculations.  From the documentation (`?logFC`):

> The log-fold change is defined as follows. For each gene, let u(x) be the expected value of the continuous component, given a covariate x and the estimated coefficients coefC, ie, u(x)= crossprod(x, coefC). Likewise, Let v(x)= 1/(1+exp(-crossprod(coefD, x))) be the expected value of the discrete component. The log fold change from contrast0 to contrast1 is defined as
> 
> u(contrast1)v(contrast1)-u(contrast0)v(contrast0).

If you don't center pc_mito then the log fold change (by default) is going to be  u(Intercept, Hist = 1, pc_mito = 0, cngeneson = 0)v(Intercept, Hist = 1, pc_mito = 0, cngeneson = 0)  - u(Intercept, Hist = 0, pc_mito = 0, cngeneson = 0)v(Intercept, Hist = 0, pc_mito = 0, cngeneson = 0)

The random effect is probably playing a role here, too, since `hist` appears to be a function of `individual`.

**Comment by combiz** [comment]
Thanks for the pointers.  We have indeed centred and scaled pc_mito as per the vignette recommendation for glmer.  Your point about the random effect for this model is interesting; hist is indeed highly correlated with individual according to the CCA: -
![image](https://user-images.githubusercontent.com/31043044/87707522-28673e80-c799-11ea-8790-05a3cae8bfda.png)
i.e. other than control samples with the same `hist` (histology marker) of 0, it's true that for the remaining samples, hist is a function of individual. This is unlike our typical categorical dependent variable model (e.g. `~diagnosis+(1|individual)+cngeneson+pc_mito`) and perhaps argues for dropping the random effect for individual in this case.

**Comment by combiz** [comment]
Very pleased to confirm that everything has fallen into place after dropping the `(1 | individual)` term and switching from `glmer` to `glm`.  The logfc values now make sense and are consistently corroborated by the scatter/jitter plots.  Thanks for your comments Andrew.
