### ISSUE TITLE
Restricted Maximum Likelihood or Maximum Likelihood for estimating parameters in mixed effect model using MAST?

### ISSUE THREAD

**Issue by sofiapuvogelvittini** [RGLab/MAST#157]
Dear MAST team,
I would like to ask you a question..
I am using MAST for modelling gene expression in a snRNAseq data, with a random intercept for subjects identity. I am wondering if in this case, the parameters are still estimated with LM ( as mentioned in the paper) or does it automatically switch to RELM?
I would like to use ML as I want to select the best model based on the deviance of the residuals.

My formula is the following
zlmCond<-MAST::zlm(~condition + cenegeneson + test_var1 + test_var2 + test_varx + (1|donor_id), data, method=´glmer´,ebayes=FALSE)

Thanks for your help!

**Comment by amcdavid** [comment]
Try `zlm(..., method ='glmer', fitArgsC=list (REML=FALSE))`. You can pass
other arguments with `fitArgsC` and `fitArgsD`.

**Comment by whreitsma** [comment]
Hello,

I tried using the solution mentioned by amcdavid, but it results in the error:
```R
Error in (function (formula, data = NULL, REML = TRUE, control = lmerControl(),  : 
  formal argument "REML" matched by multiple actual arguments
```
I made a code snippet to reproduce the error:
```R
data(maits, package='MAST')
sca <- FromMatrix(t(maits$expressionmat), maits$cdat, maits$fdat)
conditional_model <- zlm(~(PercentToHuman:condition)+ (1|condition), sca, exprs_value='et', method = 'glmer', ebayes = FALSE, fitArgsC=list(REML=FALSE))
```
I am using MAST version 1.20 on R version 4.1.1

Am I using fitArgsC wrong, or could it be something else entirely?

Thanks in advance.

**Comment by amcdavid** [comment]
Hmm, actually it looks like I had set [`REML = FALSE`]( https://github.com/RGLab/MAST/blob/6f5d763983d8087447d9ab8f6d47745ec4fcf810/R/lmWrapper-glmer.R#L237).
This now can be overridden with `fitArgsC` in the latest development version 31603fe
