### ISSUE TITLE
GSEA background sets of genes

### ISSUE THREAD

**Issue by sofiapuvogel** [RGLab/MAST#159]
Dear MAST team,
I am performing GESEA with MAST, but it is not clear to me what the program uses as "background gene sets". I am following the MAIT Analysis tutorial, with min_gene_in_module <- 5.
Best regards,
Sofía

**Comment by amcdavid** [comment]
Hi Sofia,

These are competitive tests, so the background is everything that is in the SingleCellAssay object, that is not in the set currently being tested.  The 2015 paper has the details: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0844-5#Sec12

**Comment by sofiapuvogel** [comment]
Thanks!
