### ISSUE TITLE
Comparisons among three conditions

### ISSUE THREAD

**Issue by sofiapuvogel** [RGLab/MAST#161]
Hello MAST team,
I would like your guidance about how would you compare gene expression among three different conditions. 
For example two different tratments and a control group.  Hence, levels of tratment are ("control", "treatment_A"," treatment_B")
I already tried to run the model with "control" as the reference level:
zlmCond<- MAST::zlm(~treatment + cngeneson + (1|donor_identity), method="glmer", ebayes=FALSE)
summaryCond<-summary(zlmCond, doLRT=c("treatment_A", "treatment_B"))
With this I  obtain the coefficients and p-values for each tratment (A and B), regarding the control group. But then if I also would like to know the difference between treatment_A" and "treatment_B", Should I run this again but just changing the reference level for one of the treatment groups? Or there is a more "elegant" way to compare simultaneosly the three different groups? What would you suggest?

Thanks a lot for your time and for your cool package.
Best regards,
Sofía

**Comment by amcdavid** [comment]
Please follow the instructions on our README to open a discussion on bioconductor support.

> Getting Help
> For general questions, please submit a question to the bioconductor support site so that others can benefit from the discussion.
