### ISSUE TITLE
When I run `zlm` with several clusters, how to compare 1 cluster versus all the others?

### ISSUE THREAD

**Issue by danli349** [RGLab/MAST#165]
When I run `zlm` with several clusters (I have clusters 1-7), how to compare 1 cluster versus all the others?
```
zlmCond <- zlm(formula = ~leiden_r0.3 + n_genes, sca=sca, method = "glm")
1_vs_others <- summary(zlmCond, logFC = TRUE, doLRT = 'leiden_r0.31')
```
Error Term(s) 'leiden_r0.31 ,' not found.
Terms available: (Intercept) , leiden_r0.32 , leiden_r0.33 , leiden_r0.34 , leiden_r0.35 , leiden_r0.36 , leiden_r0.37 , n_genes

**Comment by amcdavid** [comment]
Please follow the instructions in the README and post your programming issues to support.bioconductor.org.
