### ISSUE TITLE
FindAllMarkers issue

### ISSUE THREAD

**Issue by andrew2k** [RGLab/MAST#176]
Seurat  4.2.0
MAST  1.22.0
Bioconductor  3.15 

When I call FindAllMarkers(..., test.use = "MAST") function,  I get the following warning and zero DE genes:
Warning: When testing 16 versus all:
invalid name for slot of class "BayesGLMlike": norm.method

Thx a lot

**Comment by amcdavid** [comment]
Apparent duplicate of #175.
