### ISSUE TITLE
Extend SummarizedExperiment to create SingleCellAssay class

### ISSUE THREAD

**Issue by gfinak** [RGLab/MAST#59]
We'll replace DataLayer with SummarizedExperiment.
Extend SummarizedExperiment into SingleCellAssay
Ensure all existing methods work.

**Comment by gfinak** [comment]
We will need to re-write split to split on columns rather than rows.

**Comment by amcdavid** [comment]
Closed in 63c98

**Comment by gfinak** [comment]
Vignettes are currently broken. 
No function FluidigmAssay
