### ISSUE TITLE
thresholdSCRNACountMatrix 

### ISSUE THREAD

**Issue by jhsiao999** [RGLab/MAST#61]
Hi Andrew and Greg,

We are interested in trying out MAST on some of our single-cell data, but I got an error while installing MAST: unexpected symbol in line 126. Upon a closer look, the `thresholdSCRNACountMatrix` function (in `thresholdscRNA.R`) is missing a comma after adj = 1 in the arguments.

Thanks,
Joyce Hsiao

**Comment by jhsiao999** [comment]
Thanks for the quick response, Greg! I found another extra comma in `thresholdSCRNACountMatrix` after the last function argument... (after G=2).

**Comment by amcdavid** [comment]
I think this was my bad--I mistakenly merged some code into master that doesn't below.  I'm going to revert to 8234b1.

**Comment by amcdavid** [comment]
Closed in 866923.  Joyce, please let me know if you are still having any problems.

**Comment by jhsiao999** [comment]
The package was just installed successfully. Thanks Andrew!
