### ISSUE TITLE
thresholdSCRNACountMatrix is brittle with small sample sizes

### ISSUE THREAD

**Issue by amcdavid** [RGLab/MAST#64]
1.  If the min_per_bin argument is actually used, then we attempt to index into non-existent elements of the `cutpoints` list
2.  `vals2` is null sometimes and perhaps should not be
3.  Try to guess if the data has been log transformed or not.

**Comment by gfinak** [comment]
Do you have some example data we can use to debug?

**Comment by gfinak** [comment]
I've pushed a possible fix. Needs more testing, but there was an index out of bounds in a loop that organized the ordering of the thresholds,

**Comment by amcdavid** [comment]
Closed in 9c3255f
