### ISSUE TITLE
Need function to convert old MASTClassic objects to new MAST objects

### ISSUE THREAD

**Issue by gfinak** [RGLab/MAST#65]
Seems a reasonable way to do this would be to have  a function that:
1. changes the class of the old object to "array",
2. Extracts each dimension as a separate matrix to be plugged into the assay slot of summarizedExperiment
3. Extracts the phenoData, featureData and cellData attributes of the old object and assigns them to the rowData and colData of the new object.
All the above can be done with calls to attr().

**Comment by amcdavid** [comment]
Agreed that MAST 1.0 does need this.  Should we merge master into devel and start working there?  At the moment, I'm not even exactly sure what happens if you load a MASTClassic object--I would guess an obscure error?

**Comment by gfinak** [comment]
I'll push this fix shortly to master. I'll let Andrew handle branch merging, need to consider what's linked to the Bioconductor svn.

Greg Finak
