### ISSUE TITLE
Using MAST for Time Course analysis for RNAseq data

### ISSUE THREAD

**Issue by Rahel14350** [RGLab/MAST#71]
Dear Mr./Mrs.

I have RNAseq data from 2 treatments and 7 time points. I would like to find out if there is a linear response between time and gene expression in response to treatments (time as a continuous variable). 
I see interested papers with this model using MAST for Single cell analysis. Can I use this package also for normal RNAseq data (count data produced by salmon or HtSeq)?
Many thanks in advance and wish you a happy new year,
Rahel

**Comment by amcdavid** [comment]
Hi Rahel,

There's nothing keeping you from using it with ordinary RNAseq data, and it
might be especially appropriate if there is lots of zero-inflation.  But
typically bulk RNAseq doesn't really follow a zero-inflated normal
distribution like MAST assumes.  The packages limma/voom, edgeR or DESeq2
would be what I reach for first.  All of those let you do arbitrary linear
modeling.

-Andrew

**Comment by Rahel14350** [comment]
Dear David,
Thanks for your prompt reply. I have done some sort of arbitrary linear modeling for time courses in DeSeq2 but I wanted to try MAST to compare with what I did wirh DeSeq2. On the other hand, I am interested in the visualization methods in MAst for PCA and DEGs for each time point separately. I will try to combine the results from DeSeq2 with the visualization in MAST. I hope it works ...
Many thanks,
Rahel
