### ISSUE TITLE
DESCRIPTION lacks SummarizedExperiment dependency

### ISSUE THREAD

**Issue by stela2502** [RGLab/MAST#73]
Hi,
please add SummarizedExperiment as bioc dependency in your package.

**Comment by amcdavid** [comment]
Hi @stela2502 ,
It is a dependency, see [line 27 of the DESCRIPTION](https://github.com/RGLab/MAST/blob/master/DESCRIPTION).  Can you clarify?

**Comment by stela2502** [comment]
Hi,

sure, instead of putting it in

Depends:
     SummarizedExperiment

Put it under

biocViews:
    SummarizedExperiment

Then it will be installed correctly.


/Stefan



Am 2017-04-28 um 16:17 schrieb Andrew McDavid:

**Comment by gfinak** [comment]
By what mechanism are you installing packages (biocLite(), or
install.packages())?

**Comment by gfinak** [comment]
Jumping ahead here, I want to say that adding packages to biocViews in DESCRIPTION in order to get them to install using `install.packages` works, but is not a documented feature.
The better approach is to use `setRepositories()`, then `install.packages` will work as expected.

**Comment by amcdavid** [comment]
Hrm, yeah, that's definitely not how biocViews [is documented](https://www.bioconductor.org/developers/how-to/biocViews/) for use, nor is it convention in other bioconductor packages that I see.   What's wrong with `BiocInstaller::biocLite()`?

**Comment by stela2502** [comment]
Thank you!

I am surprised, that the use of biocView does work for my package. I can 
not remember where I have found the idea to use this tag.
It is working and I do not plan to submit my packages at the moment.

Thank you for the link.

/Stefan
