### ISSUE TITLE
Change to a meaningful progress bar from zlm?

### ISSUE THREAD

**Issue by Shians** [RGLab/MAST#81]
Thanks for the package! I'm wondering if it's possible to have a more informative progress bar when running `zlm()`. Right now it outputs a dot every 20 genes, it's pretty hard to interpret this meaningfully. Instead a verbal log or progress bar would be much more useful.

Either
    
    100/12345 genes processed
    200/12345 genes processed
    300/12345 genes processed
    ...

or using [txtProgressBar](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/txtProgressBar.html) with `style = 3`. Example:

    testit <- function(x = sort(runif(20)), style = 3, ...)
    {
        pb <- txtProgressBar(...)
        for(i in c(0, x, 1)) {Sys.sleep(0.5); setTxtProgressBar(pb, i)}
        Sys.sleep(1)
        close(pb)
    }
    testit()

**Comment by gfinak** [comment]
We don't have the bandwidth at the moment to work on this feature. If it's important to you, you're welcome to work on the feature and submit a pull request.

**Comment by amcdavid** [comment]
Closed in 29f58f49a48b0a3cebb6552cfc621f029b196669
