### ISSUE TITLE
non-conformable arrays error in MAST::summary v1.2.1

### ISSUE THREAD

**Issue by eleanorahowe** [RGLab/MAST#82]
Hi there, 

I've got an error when using summary on the latest version of MAST (v1.2.1). 

When I run zlm and then MAST::summary on the resulting zlm.fit object, the new version of MAST throws an error that the old version does not throw. I've attached it and the stacktrace below. 

Thing is, I also get this error when I run the zlm fitting step using the old version of MAST (1.0.5), and then use that fitted zlm object as input to the new version of MAST::summary. So I'm guessing the problem is in the summary function somewhere, rather than in the output from zlm. 

Now granted, I used two different machines to do these tests - the one with the older MAST also has older R and Bioconductor. I've attached the code I used to test these things, and the sessionInfo from the two machines I did my testing on. It uses the same example dataset I submitted in the previous thread on parallelization. 

Have you folks seen this before? Any suggestions about what's going on here? 
Eleanor

 > old.sum.lrt <- MAST::summary(oldzlm, doLRT = T)
Combining coefficients and standard errors
Calculating log-fold changes
Calculating likelihood ratio tests
Refitting on reduced model...
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Done!
Error in o0@loglik - o1@loglik : non-conformable arrays
> traceback()
9: .lrtZlmFit(object, newMM, hypothesis@.Data)
8: lrTest(object, CoefficientHypothesis(x))
7: lrTest(object, CoefficientHypothesis(x))
6: FUN(X[[i]], ...)
5: lapply(doLRT, function(x) lrTest(object, CoefficientHypothesis(x))[,
       , "Pr(>Chisq)"])
4: lapply(doLRT, function(x) lrTest(object, CoefficientHypothesis(x))[,
       , "Pr(>Chisq)"])
3: .local(object, ...)
2: MAST::summary(oldzlm, doLRT = T)
1: MAST::summary(oldzlm, doLRT = T)

[sessionInfoOld.txt](https://github.com/RGLab/MAST/files/1308357/sessionInfoOld.txt)
[sessionInfo.txt](https://github.com/RGLab/MAST/files/1308354/sessionInfo.txt)
[examplecode.zip](https://github.com/RGLab/MAST/files/1308362/examplecode.zip)

**Comment by amcdavid** [comment]
Hi Eleanor,

I'm a little confused.  Can you provide a minimal, reproducible example of this when you fit with MAST 1.2.1 from start to finish?  This behavior is not occurring in general, because that bit of code is exercised when the vignette is built, as well as in at least one unit test.

**Comment by eleanorahowe** [comment]
Hi Andrew, 

Apologies, I think something got mixed up in my version control here; I can't replicate this error anymore. If I find it again I'll open another issue. 

Eleanor
