### ISSUE TITLE
MAST error with Seurat

### ISSUE THREAD

**Issue by gresteban** [RGLab/MAST#85]
Hello,

When running:

`FindMarkers(object = seurat, ident.1 = 0, ident.2 = 1, min.pct = 0.25, test.use = "MAST", latent.vars = "nGene")`

I get the following error:

> Error in inherits(data, "SingleCellAssay") : 
>   argument "data" is missing, with no default

Differential expression is working fine with the default test ("wilcox") and with `test.use = "DESeq2"`.

Thanks for your help.

**Comment by gfinak** [comment]
Can you post the `traceback()` of that error so we can see the line and call stack in order to track it down?

**Comment by gresteban** [comment]
`traceback()`shows:

```
4: inherits(data, "SingleCellAssay")
3: MAST::zlm(formula = fmla, sca = sca, ...)
2: MASTDETest(object = object, assay.type = assay.type, cells.1 = cells.1, 
       cells.2 = cells.2, genes.use = genes.use, latent.vars = latent.vars, 
       ...)
1: FindMarkers(object = seurat, ident.1 = 0, ident.2 = 1,
       test.use = "MAST", latent.vars = "nGene")
```

**Comment by amcdavid** [comment]
What does `sessionInfo` report?

**Comment by gresteban** [comment]
You're right **amcdavid**, since I had an R version < 3.4, an old version of MAST was installed. Once I've updated R and MAST it works like a charm.

Thank you very much for pointing me in the right direction and sorry for the inconvenience, I should have realized before asking.
