### ISSUE TITLE
Using zlm without sca object

### ISSUE THREAD

**Issue by adnbps** [RGLab/MAST#87]
Instead of using MAST so that each gene is a different response variable:
    (Gene i) ~ (Covariate 1)

Is there a simple way to use MAST so that each gene is a separate predictor variable?
    (Covariate 1) ~ (Gene i)

I have tried doing this directly with the zlm function (giving it a dataframe instead of an SCA object), but the return value is a little strange. Instead of returning an S4 object with the following slots:

 [1] "coefC"              "coefD"              "vcovC"             
 [4] "vcovD"              "LMlike"             "sca"               
 [7] "deviance"           "loglik"             "df.null"           
[10] "df.resid"           "dispersion"         "dispersionNoshrink"
[13] "priorDOF"           "priorVar"           "converged"         
[16] "hookOut"

It returns a list with the following components:
[1] "cont" "disc"

I have also tried running MAST separately for one gene at a time, but this is incredibly slow, so I was wondering if there is another solution. Thanks!

**Comment by gfinak** [comment]
If gene i is a predictor and covariate i is on the left side of the equation (and is something other than single-cell gene expression), then you are no longer modeling gene expression as your outcome, but whatever your covariate i is, and that would be a different model, and not the domain of MAST. 

If, on the other hand, you mean that you would like to model gene X as the outcome and gene Y as the predictor, then the only way to do that at the moment would be to store the gene expression of genes that you want to include as predictors as new columns of the cell-level metadata (in addition to the expression matrix). You could then refer to them in the model specification.

**Comment by adnbps** [comment]
Thanks for the quick response gfinak.

Yes, I am trying to model gene X as the outcome and gene Y as the predictor.

I tried doing it as you suggested, but for some reason, this is much slower (even though I am fitting the same number of models). Any ideas why?

**Comment by gfinak** [comment]
Can you provide an example of what you are doing? How you set up the data, etc? Maybe some timings..

**Comment by gfinak** [comment]
Just checking the obvious - are you sure that the predictors are treated as numerical variables and not factors?

**Comment by adnbps** [comment]
The way I normally run MAST is I first create my data, covariates, and intercepts. The covariates I'm using are "nGene" and "condition". So I would create:

old_data = [N cells x M genes] expression matrix
old_covariates = [N cells x 2] covariates matrix
fdata = rep(1, N)

Then I would create an SCA object:
sca = MAST::FromMatrix(old_data, old_covariates, fdata)

And zlm runs pretty fast:
zlm.obj = zlm(~ nGene + condition, sca)

----------

Now, I am doing things slightly differently. There are T target genes whose expression I am trying to predict. So now:

new_data = [N cells x T genes] expression matrix
new_covariates = cbind(old_data, old_covariates) 
sca = MAST::FromMatrix(new_data, new_covariates, fdata)

And now to run zlm, I do this:
zlm.objs = sapply(colnames(new_data), function(target_gene){
    formula = as.formula(paste('~ nGene +', target_gene))
    zlm(formula, sca)
})

But this is running VERY slow...

**Comment by gfinak** [comment]
Yes, you are calling zlm  `ncol(new_data)` times (fitting `ncol(new_data)` models).
But if you just fit one model.. does the `target_gene` coefficient indicate it is treated as a continuous or discrete variable? what is the `class(new_covariates)` and what is the `mode()` of the new columns you have added?

**Comment by adnbps** [comment]
gfinak, I fixed a few mistakes in my previous post, but it sounds like you got the gist.

There query_gene coefficients suggest it is being treated as a continuous variable (there is only one coefficient - NOT one for each "level").

class(new_covariates)
[1] "data.frame"

The mode of each column is "numeric"

**Comment by gfinak** [comment]
Just so I'm clear, a single model fit is significantly slower? And if you try centering and scaling the predictors, does that help?

**Comment by amcdavid** [comment]
So in the end, you are running m^2 regression models with the 'sapply' bit.  Yes, this will be m-times slower than running zlm a single time (which actually is itself running it m-times).  I have done this on occasion.  Do you actually want every single gene to appear on the left-hand side of the regression?  Or just a single gene, on which you run m-1 different regressions with different "covariates"?

**Comment by adnbps** [comment]
Running MAST as normal, it would usually take less than 1 minute to fit ~5,000 genes (i.e. 5,000 models).

However, this is taking ~2 seconds per gene, so roughly 3 hours for ~5,000 genes.

**Comment by adnbps** [comment]
amcdavid, I am only running it on 2 target genes (i.e. T = 2)

**Comment by amcdavid** [comment]
I see.  There is overhead in zlm in creating the S4 object which may explain why it's so much slower.  As you saw, there is a data.frame method that may avoid this overhead. Or you could "invert" the model and use target gene 1, and target gene 2 each as covariates (running zlm twice). Then regress those as predictors on the whole gene matrix (M) times.  This is a different statistical model, but still answers a similar scientific question.

**Comment by adnbps** [comment]
amcdavid, running with a dataframe is incredibly fast, but I'm not sure how to get the other MAST output (logFC etc). Any ideas?

**Comment by amcdavid** [comment]
It would require some hacking.  Essentially one would need to glue together the results from calling the data.frame method repeatedly into something resembling a ZlmFit object.  How about the idea of inverting the model and using target gene 1, and target gene 2 each as covariates?

**Comment by adnbps** [comment]
amcdavid, I considered that approach, but I don't think it is technically correct. 

Would it be difficult to make a ZlmFit object? Is there a good example of how it's done?

**Comment by amcdavid** [comment]
No, it's not difficult.  It's basically just a bunch of concatenating the output from the individual fits into appropriately-shaped matrices and arrays, but since it's an internal function to the package there's not any documentation or examples aside from reading the source code.  Take a look at [line 168 onward in AllClasses.R](https://github.com/RGLab/MAST/blob/a079646898349315a676b56b6a77ca7dd17ec449/R/AllClasses.R#L168) where the ZlmFit class is defined and [lines 3-18 of ZlmFit.R](https://github.com/RGLab/MAST/blob/a079646898349315a676b56b6a77ca7dd17ec449/R/ZlmFit.R#L3) where the components from a list of fits is glued together.  Once you have assembled the slots in the requisite format, you would call new('ZlmFit', coefC=matrix_of_coefC, coefD=matrix_of_coefD, <other slots you need to fill>).  Working in your favor is a lack of validity checks for the slots, so you can add only the pieces you require (probably just `coefC`, `coefD`, `vcovC` and `vcovD` if all you care about is calculating log-fold changes).

I must admit my interest is a bit piqued over your comment that only the "target gene as response" regression model is technically correct.  What is your scientific question, anyways, if you don't mind me asking?

**Comment by adnbps** [comment]
Thanks! I finally got around to trying this.

Sorry if this is a dumb question, but how do I get the "vcovD" and "vcovC" from the simplified call? Here are the components of the list that zlm returns:

coefficients
residuals
fitted.values
effects
R
rank
qr
family
linear.predictors
deviance
aic
null.deviance
iter
weights
prior.weights
df.residual
df.null
y
converged
boundary
prior.mean
prior.scale
prior.df
prior.sd
dispersion

**Comment by amcdavid** [comment]
Hi-

vcovC and vcovD are arrays consisting of the variance-covariance matrices of continuous and discrete components.  Adapting the example in the documentation:

```
data(vbetaFA)
     zlmVbeta <- zlm(~ Stim.Condition, subset(vbetaFA, ncells==1)[1:10,])
dim(zlmVbeta@vcovC) # 2 x 2 x 10 array : coefficients x coefficients x genes
dim(zlmVbeta@vcovD) # 10 x 2 matrix: genes x coefficients

# make empty coefficient matrices and arrays
ngenes = nrow(vbetaFA) # however many times you are rerunning zlm
ncoefs = 2 # however many coefficients your fit returns
coefC <- coefD<- matrix(NA_real_, nrow = ngenes, ncol = ncoefs)
vcovC <- vcovD <- array(NA_real_, dim = c(ncoefs, ncoefs, ngenes))
data = data.frame(y = assay(vbetaFA)[1,], x = assay(vbetaFA)[2,])
for(g in seq_len(ngenes - 1)){
data$x = assay(vbetaFA)[g+1,]
     fit_dataframe <- zlm(y ~ x, data)
# may need to wrap this in a "try" block to catch cases where a coefficient is NA?
coefC[g+1,] = coef(fit_dataframe$cont)
coefD[g+1,] = coef(fit_dataframe$disc)
vcovC[,,g+1] = stats:::vcov.glm(fit_dataframe$cont)
vcovD[,,g+1] = stats:::vcov.glm(fit_dataframe$disc)
# end try block?
}
dimnames(vcovC) <- dimnames(vcovD) <- list(names(coef(fit_dataframe$cont)), names(coef(fit_dataframe$cont)), rownames(vbetaFA))
dimnames(coefC) <- dimnames(coefD) <- list(rownames(vbetaFA), names(coef(fit_dataframe$cont)))
 my_zfit = new('ZlmFit', sca = vbetaFA, coefC = coefC, coefD = coefD, vcovC = vcovC, vcovD = vcovD)
summary(my_zfit)
```
