### ISSUE TITLE
gseaAfterBoot function details

### ISSUE THREAD

**Issue by dmoaks** [RGLab/MAST#88]
Hi, 
Can you provide details of the calculations gseaAfterBoot is doing with zlmFit to generate the file "gsea"? It is not clear what the values represent, unless I am missing some documentation.
Thanks so much,
Dan Moakley

**Comment by dmoaks** [comment]
by zlmFit I meant zlmCond, as it is named in the MAIT vignette.

**Comment by amcdavid** [comment]
Hi-- Can you please repost to the bioconductor support forum: https://support.bioconductor.org/ <https://support.bioconductor.org/> so that others can benefit from the question/response after the issue is closed?

**Comment by dmoaks** [comment]
sure, just posted.
