### ISSUE TITLE
primerid is converted to integer for Hurdle component when summarising ZlmFit object

### ISSUE THREAD

**Issue by uhlitz** [RGLab/MAST#92]
minimal example:

```
library(MAST)
sce_test <- readr::read_rds(url("http://toconclu.de/sce_test.rds"))
sca <- new("SingleCellAssay", sce_test)
zlmCond <- zlm(~transgene, sca)
summaryCond <- summary(zlmCond, doLRT='transgeneKRAS') 
sdt <- summaryCond$datatable
sdt[sdt$component == "H",][1:10,]
sdt[sdt$component == "logFC",][1:10,]

```

thanks for your work, great package!

**Comment by amcdavid** [comment]
Oh, that is strange, and does relate to needing a constructor/coercion method.

**Comment by amcdavid** [comment]
Fixed in ba5f0b3b35cbaeb03a7d3ee10aa5735b64aa341f.  We expect a column in rowData named primerid, this is ensured by calling the coercion method.

```
sce_test <- readr::read_rds(url("http://toconclu.de/sce_test.rds"))
sca <- SceToSingleCellAssay(sce_test)
zlmCond <- zlm(~transgene, sca)
summaryCond <- summary(zlmCond, doLRT='transgeneKRAS') 
sdt <- summaryCond$datatable
sdt[sdt$component == "H",][1:10,]
sdt[sdt$component == "logFC",][1:10,]
```

**Comment by amcdavid** [comment]
I will add that if you don't want to use devel, a workaround is to call `FromMatrix(assays(sce_test), colData(sce_test), rowData(sce_test))`.  You may have to fiddle with the assaynames though.

**Comment by uhlitz** [comment]
Thanks for the fix, plug&play with `scater` works smoothly now. There's a typo in your function name though, should be SceToSingleCellAssay and not SceToSingleCellAsssay :)

**Comment by gfinak** [comment]
The typo is fixed in the master branch now.
